name: Update Main Branch
on:
  push:
    branches:
      - test-autocommit
permissions:
  contents: write
  pull-requests: write
jobs:
  automaticUpdating:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: test-autocommit
      - name: Reset autocommit branch
        run: |
          git fetch origin main:main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: main