name: Compile and Deploy

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      importAll:
        default: false
        required: false
        type: boolean
        description: Enable, if you want to import all TODOs. Runs on checked out branch! Only use if you're sure what you are doing.

permissions:
  issues: write
  repository-projects: read
  contents: write

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  compile:
    if: github.ref != 'refs/heads/live'  # Run on all branches except live
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install deps and build
        run: |
          npm i
          npm run build

      - name: Create commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 🤖 Compile website

  todos:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' # Run only on main or master branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Issue Bot
        uses: juulsn/todo-issue@main
        with:
          excludePattern: '^(node_modules/)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    if: github.ref == 'refs/heads/live' # Run only on live branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout live branch
        uses: actions/checkout@v4
        with:
          ref: live

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install deps and build
        run: |
          npm i
          npm run build

      - name: Sync changes to main
        uses: jojomatik/sync-branch@v2
        with:
          source: "live"
          target: "main"
          strategy: "merge"
          resolve_conflicts: "false"
          git_committer_name: darkscar
          git_committer_email: 41898282+github-actions[bot]@users.noreply.github.com

      - name: Make pull request in case of failure
        if: failure()
        uses: sansx/sync-branches@v1.0.1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "live"
          TO_BRANCH: "main"
          PULL_REQUEST_TITLE: "🔃 SYNC MAIN WITH LIVE"

      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          dist_dir: public # specify the directory where your site is built