name: Minify Workflow
on:
  push:
    branches: [ compress ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      # Job for Minify-JS
      - name: Minify-JS Action
        uses: jossydevers/minify-js@v1.0.0
        with:
          directory: 'files' # (OPTIONAL)
          output: 'public' # (OPTIONAL)
          
      # Auto-commit to repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'you already know we on that minification type stuff'
          branch: ${{ github.ref }}